### PR TITLE
DI_Condensor_23_30 modification for 30 mm lens

### PR DESCRIPTION
**Pull request by Srinivas-Ganti**
modified DI_Condensor_23_30  model to allow better fit to 30 mm lens

### CODE REVIEW

**Comment by TadPath** [comment]
Hello. Thanks for this. I am looking into it. However I cannot see the parametric model for the part - just a single volume - and I cannot see a difference with the original. But it is hard to compare. I need you to submit the parametric model with the modifications you made so I can compare to my original. Also I can only merge parametric models - the PUMA ethos is not to supply meshes but editable models for all parts. I tried to express this in the CONTRIBUTING.md doc but maybe I was not clear. Please resubmit with parameteric model in the FreeCAD file or explain to me how I can extract it from the file you sent. Thanks.

**Comment by Srinivas-Ganti** [comment]
Hello Paul,

Sorry about that. Will need to spend some time on Freecad to deliver this in the correct form. I wasn't sure how to perform the operations I needed in Freecad, I haven't used it much. I used Fusion 360 (which is also free for personal use). It has the "offset face" operation that's very intuitive and easy to use. I included 2 images in the images folder of my commit on github to illustrate these operations that completed the mod for me. I will try today and send the freecad parametric file if I am successful. When I open your freecad file , or any freecad file, I cannot see the history of operations like a timeline and usually it is only the final solid body that can be found (exceptions are some boolean cuts, but even there I don't see the sequence of operations from the beginning, or maybe I don't understand how to use this tool properly yet). I will try freecad again and get back to you. Just want to add that for people new to CAD, Fusion 360 is orders of magnitude more easy to use and beginner friendly, and more versatile for making assemblies (It's so much easier than freecad, would recommend it).

 You can also see the entire sequence of operations on your model as a design history timeline and you can roll it back to any point to change it too. I haven't figured out how to do this or similar in Freecad so could never tell how one arrived at the final form of the model. Will try again today and get back to you.

Thank you.

Best,
Srinivas

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TadPath** [comment]
OK. I amsure F360 is good but I had to make a choice for the project and I chose FreeCAD so this is what I will stick with. I think 'ease of use' depends a lot on experience with a product - I can rapidly make complex things with FreeCAD but that is because I have a lot of experience with it. As far as I know FreeCAD has no roll-back facility but is fully open source and free for all - no commercial aspect. Right now I use FreeCAD v0.19. You open up the model like a tree using the little arrow triangles on the left in the 'combo view'.
If it it difficult or too time consuming, do not worry - just let me know and I will do the changes myself based on the info you supplied (although sadly then you would not get the credit for making the pull/merge but I can put a note in the ReadMe to credit you).

**Comment by Srinivas-Ganti** [comment]
Indeed, that is only my personal view and you are right that it is just a matter of practice, I might grow to learn and love Freecad too. Thank you for explaining the tree structure of the file, that helped. I think I understand evolution of the document now. However, in the interest of time I think, this time it may be better if you update the file because I am having some difficulty editing the original document. I only made a tiny change to the model so dont mind about the credit. Thank you for considering the change. I am attaching my modified version of the Freecad file in zip along with screenshots of what I think are the affected parts. To do the equivalent operations on the model I performed in Fusion 360, I think

1. the IADC aperture radius needs to be reduced by 0.25 mm. 

 and

2. the UC_Ledge_solid001 and UC_Lumen001 parts hight needs to be reduced by 0.15 mm but only from the bottom side (not symmetric).

When I tried editing these fields in Freecad, the computation fails on the fillet operation higher up in the model tree. I am not sure how to fix it yet, so thought to just post this and leave it at that. Would be good to learn how to avoid such an upstream error so any comments/ suggestions would be appreciated :)



DI_23_30_mod_Freecad_operation1
DI_23_30_mod_Freecad_operation2
[Dominus_v3.1_part2.zip](https://github.com/TadPath/PUMA/files/8190599/Dominus_v3.1_part2.zip)

**Comment by TadPath** [comment]
Hello, Thanks for that. I assume you meant to say that the UC_Ledge_solid001 and UC_Lumen001 parts hight need to change by 0.25 mm (not 0.15) because in your picture you show the new height at 3.19 mm (which is 0.25 mm shorter). Correct me if I am wrong. Anyway, I made the changes - the 'trick' was to remove the initial chamfer before making edits and then raise the Z position of each of those components by 0.25 mm first before shortening them by 0.25 mm. Then  right click on the main root of the model tree and select 'recompute object' before re-adding the chamfers. [This must seem overly complex to you - but it is second nature to me!]. Anyway, I made the mods. I can't seem to attach it here so I will send it to you via email - if it is as you expect you can re-submit it as a revised pull request in your original format and I will test it. If problems let me know.

**Comment by Srinivas-Ganti** [comment]
Hi Paul,

Yes, i post the numbers backwards on accident. Thank you for making the changes and for catching my mistake. 

The IAD aperture radius reduces by 0.15 mm. The UC_Ledge_solid001 and UC_Lumen001 parts height is reduced by 0.25 mm.

"the 'trick' was to remove the initial chamfer before making edits and then raise the Z position of each of those components by 0.25 mm first before shortening them by 0.25 mm. Then right click on the main root of the model tree and select 'recompute object' before re-adding the chamfers. [This must seem overly complex to you - but it is second nature to me!]"

very much so :D 

 All this is reduced to just 2 clicks in Fusion. But I can see why you chose Freecad for PUMA, considering long term support among other things. 
 
 I wasn't sure what was causing the error when I tried to naively change the radius, and height of the parts in the model tree before. But I came across this youtube video that somehow might explain it, considering your workaround also seems to involve temporarily altering the face positions/ names (?) of the components. 
 
 https://www.youtube.com/watch?v=QSsVFu929jo


image
image

**Comment by TadPath** [comment]
OK. I have merged the request although the model recess diameter is a little too small to fit the curved brim lens I have. I will re-visit this when I get the new lenses from AliExpress and revise if necessary. Thanks.

**Pull request merged**
